
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Pessoa", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Pessoa {


    /**
     * 
     * @param request
     * @return
     *     returns org.tempuri.LoginResponse1
     * @throws PessoaLoginSecurityServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "Login", action = "Login")
    @WebResult(name = "LoginResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Login", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoginResponse")
    public LoginResponse1 login(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        LoginRequest request)
        throws PessoaLoginSecurityServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.tempuri.LogoutResponse
     * @throws PessoaLogoutSecurityServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "Logout", action = "Logout")
    @WebResult(name = "LogoutResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Logout", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Logout")
    @ResponseWrapper(localName = "LogoutResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LogoutResponse")
    public LogoutResponse logout(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        LogoutRequest1 request)
        throws PessoaLogoutSecurityServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.tempuri.IntegraPessoaResponse
     */
    @WebMethod(operationName = "Integrar", action = "http://erp.com.br/corporativo/PessoaService/Pessoa/Integrar")
    @WebResult(name = "IntegrarResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Integrar", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Integrar")
    @ResponseWrapper(localName = "IntegrarResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IntegrarResponse")
    public IntegraPessoaResponse integrar(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        IntegraPessoaRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns org.tempuri.ConsultaPessoaResponse
     */
    @WebMethod(operationName = "ConsultarIntegracao", action = "http://erp.com.br/corporativo/PessoaService/Pessoa/ConsultarIntegracao")
    @WebResult(name = "ConsultarIntegracaoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarIntegracao", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarIntegracao")
    @ResponseWrapper(localName = "ConsultarIntegracaoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarIntegracaoResponse")
    public ConsultaPessoaResponse consultarIntegracao(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        ConsultaPessoaRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns org.tempuri.ConsultaPessoaCPFCNPJResponse
     */
    @WebMethod(operationName = "Consultar", action = "http://erp.com.br/corporativo/PessoaService/Pessoa/Consultar")
    @WebResult(name = "ConsultarResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Consultar", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Consultar")
    @ResponseWrapper(localName = "ConsultarResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarResponse")
    public ConsultaPessoaCPFCNPJResponse consultar(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        ConsultaPessoaCPFCNPJRequest request);

}
