
package org.tempuri;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SecurityServiceFault", targetNamespace = "http://tempuri.org/")
public class PessoaLoginSecurityServiceFaultFaultFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SecurityServiceFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PessoaLoginSecurityServiceFaultFaultFaultMessage(String message, SecurityServiceFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public PessoaLoginSecurityServiceFaultFaultFaultMessage(String message, SecurityServiceFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.tempuri.SecurityServiceFault
     */
    public SecurityServiceFault getFaultInfo() {
        return faultInfo;
    }

}
